### PR TITLE
Correct Dlang keywords.

### PR DESCRIPTION
**Pull request by kookman**

### CODE REVIEW

**Comment by ThomasBrixLarsen** [comment]
Thanks. I don't think that dstring/string/wstring should be included in the list as they are actually aliases to *char arrays. Do we get clashes when string is used in a Cap'n Proto struct or enum?

**Comment by kookman** [comment]
I’m not sure. I just figured it was unwise to leave them unescaped as the
string types (+ size_t and ptrdiff_t) are *almost* keywords in D (being
aliases defined in object.d).

**Comment by ThomasBrixLarsen** [comment]
Could you please split this into two PRs?

**Comment by ThomasBrixLarsen** [comment]
I'm actually using string as an identifier in a project using Cap'n Proto and it works fine. If you remove "keywords" defined in object.d I'll merge the "Correct Dlang keywords." commit.

**Comment by kookman** [comment]
Ok, I've split out the properties work onto a separate branch for now (sorry, didn't intend for them to pile up on each other into this PR). I've removed the aliases from the keyword lists. I think this should be good to go now.

**Pull request merged**
